storage:
  init:
    path: classpath:data/data.json
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:6432/test_db
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl.auto: update
  properties:
    hibernate:
      implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy


logging:
  level:
    org.hibernate: DEBUG
    org.springframework.orm.jpa: DEBUG