storage:
  init:
    path: classpath:data/data.json
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:6432/test_db
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

hibernate:
  ddl-auto: update
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  format-sql: true
  jdbc:
    lob:
      non-contextual-creation: true
  temp:
    use-jdbc-metadata-defaults: false

logging:
  level:
    org.hibernate: DEBUG
    org.springframework.orm.jpa: DEBUG

