storage:
  init:
    path: classpath:data/data.json
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:6432/test_db
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  hbm2ddl.auto: update


logging:
  level:
    org.hibernate: DEBUG
    org.springframework.orm.jpa: DEBUG

